[package]
name = "harbor-ui"
version = "0.1.0"
edition = "2021"

[features]
default = []
vendored = ["rusqlite/bundled-sqlcipher-vendored-openssl"]

[dependencies]
harbor-client = { version = "0.1.0", path = "../harbor-client" }

anyhow = "1.0.89"
log = "0.4"
pretty_env_logger = "0.5" # todo swap to a file logger
iced = { version = "0.13.1", features = ["debug", "tokio", "svg", "qr_code", "advanced"] }
lyon_algorithms = "1.0"
once_cell = "1.0"
tokio = { version = "1", features = ["full"] }
palette = "0.7"
config = "0.14.0"
serde = { version = "1.0.210", features = ["derive"] }
home = "0.5.9"
chrono = "0.4.38"
rusqlite = { version = "0.28.0", features = ["sqlcipher"] }
diesel = { version = "2.1.6", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }
uuid = { version = "1.8", features = ["v4"] }
async-trait = "0.1.77"
bincode = "1.3.3"
hex = "0.4.3"

bitcoin = { version = "0.30.2", features = ["base64"] }
bip39 = "2.0.0"
fedimint-api-client = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-client = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-core = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-wallet-client = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-mint-client = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-ln-client = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-bip39 = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }
fedimint-ln-common = { git = "https://github.com/fedimint/fedimint/", rev = "54acaa63a45e6bd14e872cdaaf020e8c100d6b33" }

[dev-dependencies]
tempdir = "0.3.7"
