[package]
name = "harbor-ui"
version = "0.1.0"
edition = "2021"

[features]
default = []
vendored = ["harbor-client/vendored"]

[dependencies]
harbor-client = { version = "0.1.0", path = "../harbor-client" }
fd-lock = "4.0.2"

log = "0.4"
simplelog = "0.12"
iced = { git = "https://github.com/iced-rs/iced", rev = "940a079", features = ["debug", "tokio", "svg", "qr_code", "advanced"] }
lyon_algorithms = "1.0"
tokio = { version = "1", features = ["full"] }
palette = "0.7"
chrono = "0.4.38"
uuid = { version = "1.8", features = ["v4"] }

bitcoin = { version = "0.32.4", features = ["base64"] }
bip39 = "2.0.0"
fedimint-core = "0.5.0"
fedimint-ln-common = "0.5.0"
opener = { version = "0.7.2", features = ["reveal"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"