name: CI 

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: Swatinem/rust-cache@v2
        with:
          # Add env vars that affect the build, including our feature flag
          env-vars: CARGO USE_VENDOR_FEATURE
      - name: Run format check
        run: nix develop --command bash -c "just format-check"
      - name: Run clippy
        run: nix develop --command bash -c "just clippy"
      - name: Run tests 
        run: nix develop --command bash -c "just test"
