name: "Test Secrets"

on:
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  test-secrets:
    name: Test Secrets Access
    runs-on: macos-latest
    environment: signing
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Make script executable
        run: chmod +x scripts/test-secrets.sh

      - name: Test Secrets
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
        run: nix develop --command bash -c "./scripts/test-secrets.sh" 